[package]
name = "counter_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=2.3.1"}
counter_witness = { path = "../../../counter_witness", default-features = true}
