[package]
name = "counter_library"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-binfmt = "=2.0.2"
risc0-build = "=2.3.1"
risc0-build-kernel = "=2.0.0"
risc0-circuit-keccak = "=3.0.0"
risc0-circuit-keccak-sys = "=3.0.0"
risc0-circuit-recursion = "=3.0.0"
risc0-circuit-recursion-sys = "=3.0.0"
risc0-circuit-rv32im = "=3.0.0"
risc0-circuit-rv32im-sys = "=3.0.0"
risc0-core = "=2.0.0"
risc0-groth16 = "=2.0.2"
risc0-sys = "=1.4.0"
risc0-zkos-v1compat = "=2.0.1"
risc0-zkp = "=2.0.2"
risc0-zkvm-platform = "=2.0.3"
risc0-zkvm = "=2.3.1"


arm = { git = "https://github.com/anoma/arm-risc0", branch = "m1dnight/risc0-3.0.3", default-features = true }
counter_witness = { path = "../counter_witness"}
serde = { version = "1.0.219", features = ["derive"] }
lazy_static = "1.5.0"
hex = "0.4"
rustler = {version = "0.36.2", optional = true}

[features]
default = []
nif = ["arm/nif", "dep:rustler", "counter_witness/nif"]
